feature/KAN-19-add-entities
TeamChallenge-Projects/tc-mentality pull request #1
Opened 2024-11-08 21:29 UTC by MinoUni

https://projectdelta1410.atlassian.net/browse/KAN-7

Add entities based on a database schema

2024-11-09 14:33 UTC, Vladik-gif requested changes

2024-11-09 14:33 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/customer/Customer.java
> +
You also need to add the create_date attribute

2024-11-09 14:33 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/customer/Customer.java
you also need added spring-boot-starter-web a the pom.xml

2024-11-10 17:42 UTC, Vladik-gif requested changes

2024-11-10 17:42 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/notification/Notification.java
> +  private Integer id;
@GeneratedValue(strategy = GenerationType.IDENTITY)

2024-11-10 17:42 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/customer/CustomerWishlist.java
> +
@GeneratedValue(strategy = GenerationType.IDENTITY)

2024-11-10 17:42 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/customer/CustomerCart.java
> +  private Integer id;
@GeneratedValue(strategy = GenerationType.IDENTITY)

2024-11-10 17:42 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/product/Product.java
> +  @ManyToMany(mappedBy = "products")
Чому відношення MayToMany?

2024-11-10 17:42 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/product/Product.java
> +  @ManyToMany(mappedBy = "products")
Ось тут також, пояснити зможеш?

2024-11-10 18:09 UTC, MinoUni commented on src/main/java/io/teamchallenge/mentality/notification/Notification.java
> +  private Integer id;
Id шейриться від `Order` по 1:1 зв'язку

2024-11-10 18:12 UTC, MinoUni commented on src/main/java/io/teamchallenge/mentality/customer/CustomerCart.java
> +  private Integer id;
Те саме як і з корзниною "вподобайок"

2024-11-10 18:18 UTC, MinoUni commented on src/main/java/io/teamchallenge/mentality/product/Product.java
> +  @ManyToMany(mappedBy = "products")
Так само як і з `wishlist`

2024-11-11 09:51 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/customer/CustomerWishlist.java
> +
Так, а чому корзину ти взяв на бек, якщо можна корзину обробляти на frontend це буде краще і динамічно!

2024-11-11 09:52 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/product/Product.java
> +  @ManyToMany(mappedBy = "products")
Ну тоді потріібно робити 1:n, а не n:n!

2024-11-11 09:56 UTC, Vladik-gif requested changes

2024-11-11 09:56 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/product/Product.java
> +  @ManyToMany(mappedBy = "products")
тут щсь не так! З'язкі мені не подобаються! Треба це обговорити на міті технічному! Напиши мені в телеграм!

2024-11-11 10:09 UTC, MinoUni commented on src/main/java/io/teamchallenge/mentality/customer/CustomerWishlist.java
> +
Про такий підхід якщо чесно не чув, потрібно глянути почитати

2024-11-19 09:21 UTC, Vladik-gif requested changes

2024-11-19 09:21 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/order/Order.java
> +
Якщо це не потрібно то краще видаляти чим зберігати це!

2024-11-19 09:21 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/payment/PaymentDetails.java
> +  @OneToMany(fetch = FetchType.LAZY)
В анотації `@OneToMany` вже за замовчуванням LAZY тому можна це не писати!

2024-11-19 09:21 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/product/Product.java
> +
.

2024-12-09 14:21 UTC, merged