feat: add ci pipeline, application.yml config for testing and connection with sonarcloud
TeamChallenge-Projects/tc-mentality pull request #2
Opened 2024-11-11 13:39 UTC by MinoUni

- add CI pipeline
- add connection with SonarCloud
- add `application.yml` configuration for testing

2024-11-14 20:41 UTC, Vladik-gif requested changes

2024-11-14 20:41 UTC, Vladik-gif commented on pom.xml
> +			<groupId>com.h2database</groupId>
Навіщо нам друга база, а темпаче h2?

2024-11-15 08:43 UTC, MinoUni commented on pom.xml
> +			<groupId>com.h2database</groupId>
Не було часу налаштувати клонування бд для тестів, тому прикрутив Н2 щоб чекнути СІ

2024-11-15 12:12 UTC, Vladik-gif commented on pom.xml
> +			<groupId>com.h2database</groupId>
Зрозумів, підключай PostgresQL

2024-11-15 12:13 UTC, Vladik-gif commented on pom.xml
> +			<groupId>com.h2database</groupId>
> Не було часу налаштувати клонування бд для тестів, тому прикрутив Н2 щоб чекнути СІ

Працює CI?

2024-11-15 15:18 UTC, MinoUni commented on pom.xml
> +			<groupId>com.h2database</groupId>
Так

2024-11-15 15:25 UTC, merged