[KAN-25][Feat]: Add Google ID token validator
TeamChallenge-Projects/tc-mentality pull request #3
Opened 2024-11-27 11:01 UTC by MinoUni

2024-11-27 11:35 UTC, Vladik-gif reviewed
working?

2024-11-27 12:00 UTC, MinoUni commented
> working?

Працює, вчора локально через фронт кидав токен, але залежить від PR з ентітями (бо потрібно кудись це персістити)

2024-12-04 13:24 UTC, Vladik-gif requested changes

2024-12-04 13:24 UTC, Vladik-gif commented on src/main/java/io/teamchallenge/mentality/auth/AuthController.java
> +        .build();
`ResponseEntity<String>` краще так не писати, а просто String так буде практичней і return буде теж лаконічний

2024-12-09 15:24 UTC, merged